name: Rename the project from template

on: [push]

jobs:
  rename-project:
    if: ${{ github.repository	!= 'fifthtry/fpm-blog' && github.run_number == 1 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash
      - run: sed -i 's/fpm-blog/${{ env.REPOSITORY_NAME }}/g' FPM.ftd
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          # commit_options: '--amend --no-edit'
          push_options: --force